Fix NPE in isCompletionInsertReplaceSupport check
    java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.eclipse.lsp4j.CompletionItemCapabilities.getInsertReplaceSupport()" is null
    	at org.eclipse.jdt.ls.core.internal.preferences.ClientPreferences.isCompletionInsertReplaceSupport(ClientPreferences.java:390)
    	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalReplacementProvider.updateReplacement(CompletionProposalReplacementProvider.java:198)
    	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalReplacementProvider.updateReplacement(CompletionProposalReplacementProvider.java:120)

Signed-off-by: Mathias Fussenegger <f.mathias@zignar.net>