Fix NPE in JDTUtils.getClassFile()
java.lang.NullPointerException: Cannot invoke
"org.eclipse.jdt.core.IType.getClassFile()" because "type" is null
  at org.eclipse.jdt.ls.core.internal.JDTUtils.getClassFile(JDTUtils.java:492)
  at org.eclipse.jdt.ls.core.internal.JDTUtils.discardClassFileWorkingCopy(JDTUtils.java:478)
  at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.hover(HoverHandler.java:51)

This happens in eclipseide-jdtls, when skipProjectConfiguration=true ,
and causes an error response when decent response can be returned here.